name: Test
on: [push, pull_request]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features -- -D warnings
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --all-features
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --no-default-features --features=serde -- -D warnings
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-default-features --features=serde --all-features
